#!/usr/bin/env ruby

require "/storage/apps/git_auth/git_auth.rb"

module GitAuth

  class PreReceive
    
    def self.process

      Log.debug "In pre-receive hook"
      
      if ENV["GIT_USERNAME"].nil?
        Log.tell_user "Need GIT_USERNAME in environment"
        Log.debug "GIT_USERNAME not in environment"
        exit 1
      end
      
      while input = gets
        Log.debug "Verifying write request for user \"#{ENV['GIT_USERNAME']}\" for ref: \"#{input.split.last.strip}\""
        unless Auth.can_write?(ENV["GIT_USERNAME"], input.split.last.strip, ENV["GIT_REPO"])
      		Log.tell_user "***"
      		Log.tell_user "*** You don't have permission to push to this location"
      		Log.tell_user "***"
      		exit 1
      	end
      end

      exit 0
    end
  end
  
end

GitAuth::PreReceive.process

