#!/usr/bin/env ruby

require Dir.pwd + '/git_auth/git_auth.rb'

puts "============================================================"
puts "Verifying commit for #{`whoami`.strip}"

while input = gets
        parts = input.split

        puts "REF : " +  parts.last.strip
        if !GitAuth::Auth.has_rights? `whoami`.strip, parts.last.strip,'w'
                exit 1
        end

end

exit 0

puts "============================================================"
