#!/usr/bin/env ruby

include 'ruby_auth'

puts "============================================================"
puts "Verifying commit for #{`whoami`.strip}"

while input = gets
        parts = input.split

        if( parts.last =~ /refs\/heads\/master/ )
		puts "No direct commits to master tree"
			exit 1
        else
			exit 0
        end
        puts parts.last
end


puts "============================================================"